Implements new methods for the Icinga client
vshn/go-icinga2-client pull request #9
Opened 2022-09-15 12:53 UTC by pdorschner

This PR implements new functions which are needed for another PR in Signalilo [Add feature redundant master api](https://github.com/vshn/signalilo/pull/114)

2022-09-19 07:23 UTC, martialblog commented on icinga2/icinga.go
> +	if resp.HttpResponse().StatusCode != 200 {
@pdorschner What if we get "301 Moved Permanently"?

2022-09-30 09:51 UTC, simu requested changes
The overall goal of this PR makes sense. However, the implementation needs to be improved a bit, as it currently breaks the separation between the WebClient and the MockClient.

See my inline comments for individual suggestions.

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +}
This seems odd, the implementation for `WebClient` essentially creates a copy of the object it's called on, while the implementation for `MockClient` returns an empty WebClient. To do this properly we should extract the actual client config into its own type, and either embed that type in both `WebClient` and `MockClient`, or simply construct that type from the client on which `GetClientConfig()` is called on.

Just returning a different struct is probably easier, something like:

```suggestion
type ClientConfig struct {
	URL               string
	Username          string
	Password          string
	Debug             bool
	DisableKeepAlives bool
	Zone              string
	TLSConfig         *tls.Config
}

func (s *WebClient) GetClientConfig() ClientConfig {
	return ClientConfig{
		URL:               s.URL,
		Username:          s.Username,
		Password:          s.Password,
		Debug:             s.Debug,
		DisableKeepAlives: s.DisableKeepAlives,
		Zone:              s.Zone,
		TLSConfig:         s.TLSConfig,
	}
}

func (s *MockClient) GetClientConfig() ClientConfig {
	return ClientConfig{}
}
```

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +	GetClientConfig() WebClient
```suggestion
	GetClientConfig() ClientConfig
```

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +}
Mock implementations should never call the type they're mocking. The simplest solution here is to add field `URL` to `MockClient`.

```suggestion
func (s *MockClient) SetIcingaUrl(url string) {
	s.URL = url
}
```

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
>  type MockClient struct {
```suggestion
type MockClient struct {
	URL string
```

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +	if resp.HttpResponse().StatusCode != 200 {
I see two cases here: either the HTTP client library we're using can follow redirects, so we should never get a "301 Moved Permanently" here, or it doesn't and this library won't be able to communicate with an Icinga2 instance which replies with "301 Moved Permanently" anyway.

However, I'd use `http.StatusOK` instead of the literal `200`:

```suggestion
	if resp.HttpResponse().StatusCode != http.StatusOK {
```

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +	return nil
It makes no sense that the MockClient tries to make a HTTP request using a napping client which wasn't initialized.

Instead I'd do something like the following here:

```suggestion
	url, err := url.Parse(url)
	if err != nil {
		return err
	}
	if url.Host == "" {
		return fmt.Errorf("URL without hostname not supported: %v", url)
	}
	return nil
```

which just parses the URL and verifies that the method is called with a URL which includes a hostname.

2022-09-30 09:51 UTC, simu commented on icinga2/icinga.go
> +func (s *WebClient) TestIcingaApi(url string) error {
Having this method take a separate `url` as a parameter means that it doesn't really need to be a method on the Icinga client at all.

In my opinion, having this method not take an argument and instead testing that the URL of the client on which it is called is working would make more sense.

2022-10-10 15:10 UTC, simu approved these changes

2022-10-10 15:14 UTC, merged